name: Release - Merge Back to Dev
on:
  workflow_run:
    workflows: ['Release - Build Artifacts, Tag, and Release']
    branches: [release]
    types:
      - completed
  workflow_dispatch:

jobs:
  merge-back:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: develop
          message: 'chore: merge release to develop'
          github_token: ${{ secrets.ACTION_TOKEN }}
